// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    NavMenuItem: typeof import('./src/components/Layout/NavMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/Layout/SideNav.vue')['default']
    ToggleTheme: typeof import('./src/components/Layout/ToggleTheme.vue')['default']
  }
}
