// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsCellRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/ActionsCellRenderer.vue')['default']
    CiHamburger: typeof import('~icons/ci/hamburger')['default']
    ComponentCellRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/ComponentCellRenderer.vue')['default']
    DataTable: typeof import('./src/components/Core/DataTable/DataTable.vue')['default']
    FieldHeaderRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/FieldHeaderRenderer.vue')['default']
    FilterInput: typeof import('./src/components/Core/DataTable/FilterInput.vue')['default']
    FilterPanel: typeof import('./src/components/Core/DataTable/FilterPanel.vue')['default']
    FloatingFilterRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/FloatingFilterRenderer.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    IcBaselineDarkMode: typeof import('~icons/ic/baseline-dark-mode')['default']
    JsxCellRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/JsxCellRenderer.vue')['default']
    'La:search': typeof import('~icons/la/search')['default']
    MdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    MdiFilter: typeof import('~icons/mdi/filter')['default']
    MdiFilterVariant: typeof import('~icons/mdi/filter-variant')['default']
    MdiRefresh: typeof import('~icons/mdi/refresh')['default']
    MdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    NavMenuItem: typeof import('./src/components/Layout/NavMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionCellRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/SelectionCellRenderer.vue')['default']
    SelectionHeaderRenderer: typeof import('./src/components/Core/DataTable/RootCellRenderers/SelectionHeaderRenderer.vue')['default']
    SideNav: typeof import('./src/components/Layout/SideNav.vue')['default']
    'SystemUicons:reset': typeof import('~icons/system-uicons/reset')['default']
    ToggleTheme: typeof import('./src/components/Layout/ToggleTheme.vue')['default']
  }
}
